### ISSUE TITLE
Getting TypeError [ERR_INVALID_ARG_TYPE] on running start script

### ISSUE THREAD

**Issue by leemun1** [conditionalcoding/typescript-electron-react#2]
I got an error on running `npm run start:web` immediately after doing `npm install`.
According to a related issue [here](https://github.com/facebook/create-react-app/issues/8499), it appears that the version specified for `react-scripts` need to bumped up.

In my case, I followed a suggestion in the above issue page and changed:

##### In `package.json`:
`"react-scripts": "3.3.0",` to `"react-scripts": "3.4.0",`

The error was resolved after this change.

**Comment by tigranbs** [comment]
@leemun1  thanks for letting me know, seems I had it on my system and never realized that it could be an issue, will check that with a fresh install
