### ISSUE TITLE
Cross platform support

### ISSUE THREAD

**Issue by jkeepr** [conditionalcoding/typescript-electron-react#3]
I'm using this boilerplate on windows.

I changed:
```json
"scripts": {
    [...]
    "build:web": "PUBLIC_URL=./ react-scripts build",
    [...]
}
 ```
to
```json
"scripts": {
    [...]
    "build:web": "set PUBLIC_URL=./&& react-scripts build",
    [...]
}
 ```
to add cross platform capability.

Maybe you want to add this as well.

**Comment by tigranbs** [comment]
@jkeepr thanks for mentioning this, just added npm package `cross-env` which helps to set environment variables for windows and *nix systems.
